
ZSH=true # Will be overwritten
source ~/.dotfiles/zsh/ohmyzsh.sh

if [ "$(uname -s)" = "Darwin" ]
then
    source ~/.dotfiles/osx/locals.sh
    source ~/.dotfiles/homebrew/completion.sh
fi

#source ~/.dotfiles/python/virtualenvwrapper.inc
source ~/.dotfiles/android/path.sh
source ~/.dotfiles/appengine/appengine.sh
source ~/.dotfiles/aws/aws.sh
source ~/.dotfiles/go/go.sh
source ~/.dotfiles/functions/_dex

export PATH=$PATH:~/bin

[[ -a ~/.localrc ]] && source ~/.localrc
