# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if [ "$(uname -s)" == "Darwin" ]
then
    source ~/.dotfiles/osx/android.sh
    source ~/.dotfiles/osx/locals.sh
    source ~/.dotfiles/homebrew/completion.sh
fi

source ~/.dotfiles/python/virtualenvwrapper.inc
source ~/.dotfiles/appengine/appengine.sh
source ~/.dotfiles/aws/aws.sh
source ~/.dotfiles/go/go.sh
source ~/.dotfiles/functions/_dex

source ~/.dotfiles/bash/config.sh
source ~/.dotfiles/bash/aliases.sh

export PATH=$PATH:~/bin

[[ -a ~/.localrc ]] && source ~/.localrc
